# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20160416_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
